#!/usr/bin/python3
import argparse
import pytopdrawer


def __main__():
	parser = argparse.ArgumentParser()
	parser.add_argument("folder", type=str,help="url/file/string")
	args = parser.parse_args()
	tops = pytopdrawer.read(args.folder)
	for t in tops:
		t.show()

__main__()